"""Material Symbols used throughout the ProBooks navigation."""

SECURITY = ":material/security:"
ADD_CLIENT = ":material/person_add:"
DASHBOARD = ":material/dashboard:"
TRIAL_BALANCE = ":material/table_view:"
JOURNAL_ENTRIES = ":material/receipt_long:"
CHART_OF_ACCOUNTS = ":material/account_tree:"
IMPORT = ":material/upload_file:"
REPORTS = ":material/analytics:"
TRANSACTIONS = ":material/account_balance_wallet:"
RECONCILIATION = ":material/rule:"
AUDIT_TRAIL = ":material/history:"
CLIENTS = ":material/groups:"
REVIEW = ":material/fact_check:"
ASSISTANT = ":material/smart_toy:"
FIRM = ":material/settings:"
